//avalon
require("./avalon.js");
//组件基础库
require("./base");
//各种组件
require("./accordion/avalon.accordion");
require("./dialog/avalon.dialog");
require("./table/avalon.table");
require("./autocomplete/avalon.autocomplete");
require("./dropdown/avalon.dropdown");
require("./tooltip/avalon.tooltip");
require("./tab/avalon.tab");
require("./tree/avalon.tree");
//ajax
require("./ajax");